version: "3"
services:

  networks:
    ulm_net:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 1.80.67.0/24

  #  Create a service named db.
  postgres:
    image: postgres
#   Give the container the name my_postgres. You can changes to something else.
    container_name: postgres-rest-service
#   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD='9C4q&7$ES9X1a1M^gA4369p9C4q&7$ES9X1a1M^gA4369p9C4q&7$ES9X1a1M^gA4369p'
      - POSTGRES_DB='rest-service'
#    ports:
#      - "9432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

   networks:
      ulm_net:
        ipv4_address: 1.80.67.2
#    ports:
#      - "35432:5432"
#    expose:
#      - "5432"

  dev_rest_service:
    image: dev-rest-service
    container_name: dev-rest-service
    networks:
      ulm_net:
        ipv4_address: 1.80.67.3
      ports:
      - "9080:9080"
      expose:
      - "9080"