version: "3"
services:

  networks:
    rest_service_net:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 1.80.67.0/24

  #  Create a service named db.
  rest_service_postgres:
    image: postgres
    container_name: rest-service-postgres
    environment:
      POSTGRES_USER: "postgres_test"
      POSTGRES_PASSWORD: "9C4q&7$ES9X1a1M^gA4369p9C4q&7$ES9X1a1M^gA4369p9C4q&7$ES9X1a1M^gA4369p"
      POSTGRES_DB: "rest-service"
    volumes:
      # mkdir -r /srv/postgres_data/rest_service; chmod a+rw -R /srv/postgres_data/reset_service
      - /srv/postgres_data/rest_service:/var/lib/postgresql/data

   networks:
      rest_service_net:
        ipv4_address: 1.80.67.3
    ports:
      #- "5432:5432"
      - "35432:5432"

  rest_service_mongo:
    image: mongo:3.4.19-jessie
    container_name: rest-service-mongo
    command: --smallfiles
    networks:
      rest_service_net:
        ipv4_address: 1.80.67.4
    # ports:
    #   # Disable access to Mongo for extrernal acces
    #   # Avoid local name collisions map host:29017 -> Mongo db port
    #   - "30017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo_user"
      MONGO_INITDB_ROOT_PASSWORD: "9C4q&7$ES9X1a1M^gA4369p9C4q&7$ES9X1a1M^gA4369p9C4q&7$ES9X1a1M^gA4369p"
    volumes:
      # mkdir -r /srv/mongo_data/rest_service; chmod a+rw -R /srv/mongo_data/rest_service
      - /srv/mongo_data/rest_service:/data/db


  dev_rest_service:
    image: dev-rest-service
    container_name: dev-rest-service
    networks:
      rest_service_net:
        ipv4_address: 1.80.67.2
      ports:
      - "9080:9080"
      expose:
      - "9080"